default_stages: [commit]
exclude: ^be/

repos:
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: gofmt -l -d ./
        language: system
        always_run: true
        files: ^$
  
