default_stages: [commit]
exclude: ^be/

repos:
-   repo: local
    hooks:
    -   id: go-fmt
        name: 'go-fmt'
        entry: hooks/run-go-fmt.sh
        language: 'script'
        files: '\.go$'
        always_run: true
        description: "Runs `go fmt`"
    -   id: go-vet
        name: 'go-vet'
        entry: hooks/run-go-vet.sh       
        language: 'script'
        files: '\.go$'
        always_run: true
        description: "Runs `go vet`"  
    -   id: go-tests
        name: 'go-tests'
        entry: hooks/run-go-tests.sh
        language: 'script'
        files: '\.go$'
        always_run: true
        description: "Runs `go test`"          
    -   id: mod tidy
        name: mod tidy
        entry: go mod tidy -v 
        language: system
        always_run: true
        files: ^$  
    -   id: mod vendor
        name: mod vendor
        entry: go mod vendor 
        language: system
        always_run: true
        files: ^$ 
          #-   id: mod build
          #name: mod build
          #entry: go build go list ./...  | grep -v /vendor/
          #language: system
          #always_run: true
          #files: ^$ 
