default_stages: [commit]
exclude: ^be/

repos:
-   repo: local
    hooks:
    -   id: fmt
        name: fmt
        entry: gofmt -l -d ./
        language: system
        always_run: true
        files: ^$
    -   id: vet
        name: vet
        entry: go vet       
        language: system
        always_run: true
        files: ^$
          #-   id: lint
          #    name: lint
          #    entry: golint  
          #    language: system
          #    always_run: true
          #    files: ^$  
